### PR TITLE
Fix #67, Use `size_t` for 'size' variables

### LINKED ISSUE #67: Size variables should use the `size_t` type
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md).
* [x] I performed a cursory search to see if the bug report is relevant, not redundant, nor in conflict with other tickets.

**Describe the bug**
Most variables representing sizes in MM use `size_t.`
There are a few that do not follow this custom and could be transitioned over.

**Code snips**
https://github.com/nasa/MM/blob/b824250e2224ba5885971869c97a1706e3d2492c/fsw/src/mm_dump.c#L53
https://github.com/nasa/MM/blob/b824250e2224ba5885971869c97a1706e3d2492c/fsw/src/mm_utils.c#L299

**Expected behavior**
All size variables that can use `size_t` should do so - `size_t` is more expressive and more consistent with the relevant coding guidelines.

**Reporter Info**
Avi Weiss @thnkslprpt

### PR DESCRIPTION
**Pull request by thnkslprpt**
**Checklist**
* [x] I reviewed the [Contributing Guide](https://github.com/nasa/osal/blob/main/CONTRIBUTING.md).
* [x] I signed and emailed the appropriate [Contributor License Agreement](https://github.com/nasa/cFS/blob/main/CONTRIBUTING.md#contributor-license-agreement-cla) to GSFC-SoftwareRelease@mail.nasa.gov and copied cfs-program@lists.nasa.gov.

**Describe the contribution**
- Fixes #67 
  - Converted the obvious candidates for conversion to `size_t` (mostly local variables).
  - Updated the related local test variables to `size_t` as well for consistency.
  - All variables updated were already unsigned (`uint8,` `uint16` and mostly `uint32`).

4 functions had parameters converted to `size_t:`
`MM_Verify32Aligned()` - `uint32 Size`
`MM_Verify16Aligned()` - `uint32 Size`
`MM_VerifyLoadDumpParams()` - `uint32 SizeInBytes`
`MM_VerifyPeekPokeParams()` - `uint8 SizeInBits`

Even if using `size_t` is unnecessary in some cases (and wastes some space), it is more expressive and more compliant with the relevant coding standards.

**Testing performed**
GitHub CI actions all passing successfully.

**Expected behavior changes**
No change to behavior other than type changes outlined above.

**Contributor Info**
Avi Weiss @thnkslprpt

### CODE REVIEW

File: fsw/src/mm_dump.c [hunk 1]
```diff
@@ -103,9 +103,9 @@ bool MM_PeekMem(const MM_PeekCmd_t *CmdPtr, cpuaddr SrcAddress)
     uint16 WordValue      = 0;
     uint32 DWordValue     = 0;
     int32  PSP_Status     = 0;
-    uint32 BytesProcessed = 0;
+    size_t BytesProcessed = 0;
```
Comment (chillfig) [inline fsw/src/mm_dump.c:106]: Later on line 168, this gets assigned to `MM_AppData.HkPacket.BytesProcessed`. What do you think about changing the prototype of `MM_AppData.HkPacket.BytesProcessed` (BytesProcessed of MM_HkPacket_t in file mm_msg.h) to align with this change?

**Review by chillfig — CHANGES_REQUESTED** [review]

File: fsw/src/mm_dump.c (hunk 1 above)
Comment (thnkslprpt) [reply fsw/src/mm_dump.c:106]: Yes Justin - great addition.
I ran through and checked - that member only ever gets assigned to other `size_t`'s or `uint`'s.

File: fsw/inc/mm_msg.h [hunk 2]
```diff
@@ -87,8 +87,7 @@ typedef struct
 {
     CFE_MSG_CommandHeader_t CmdHeader; /**< \brief Command header */
 
-    uint8        DataSize;      /**< \brief Size of the data to be read     */
-    uint8        Padding[3];    /**< \brief Structure padding               */
```
Comment (chillfig) [inline fsw/inc/mm_msg.h:91]: Padding omission looks appropriate given the new variable, DataSize.

**Review by chillfig — APPROVED** [review]
Looks good to me!
